proc ds2;
package mm / overwrite=yes;
declare char(50) team;
declare integer rank year; 
method m_season(integer m) returns integer;
declare varchar(200) Team;
declare integer Rank;
declare integer r;
if 3<=m<6 then r=1;
else if 6<=m<9 then r=2;
else if 9<=m<12 then r=3;
else r=4;
return r;
end;
method venue_n(varchar(200) m) returns integer;
declare integer r;
if m='Home' then r=1;
else if m='Away' then r=2;
else r=3;
return r;
end;
method competition_n(varchar(200) m) returns integer;
declare integer r;
if m='FIFA Confederations Cup' then r=0;
if m='Friendlies (M)' then r=1;
if m='UEFA Euro' then r=3;
if m in ('UEFA Euro Qualifying' 'UEFA Nations League' 'WCQ') then r=2;
if m='World Cup' then r=4;
return r;
end;
method round_n(varchar(200) m) returns integer;
declare integer r;
if m in ('Final' 'Finals') then r=5;
else if m='Friendlies (M)' then r=0;
else if m in ('First round','Group stage','League A','League B','League C','Play-off Round') then r=1;
else if m='Quarter-finals' then r=3;
else if m in ('Round of 16','Second round') then r=2;
else if m in ('Semi-finals','Third-place match') then r=4;
return r;
end;
method shirt_n(varchar(200) m) returns integer;
declare integer r;
if m='Niclas Füllkrug' then r=1;
else if m in ('Gonçalo Ramos' 'Harry Kane' 'Artem Dovbyk') then r=9;
else if m='Romelu Lukaku' then r=90;
else if m='Ante Rebić' then r=7;
else if m='Patrik Schick' then r=10;
else if m='Roland Sallai' then r=20;
else if m='Rasmus Hojlund' then r=11;
return r;
end;
method foot(varchar(200) m) returns integer;
declare integer r;
if m in ('Gonçalo Ramos' 'Niclas Füllkrug' 'Harry Kane' 'Ante Rebić' 'Roland Sallai' 'Artem Dovbyk' 'Rasmus Hojlund') then r=1;
else if m in ('Romelu Lukaku' 'Patrik Schick') then r=2;
return(r);
end;
method squad_ranking(varchar(200) t,integer y) returns integer;
declare package hash h([team year],[rank],8,'rank');
missing(team);
missing(year);
missing(rank);
team=t;
year=y;
h.find();
return(rank);
end;
method squad(varchar(200) m) returns varchar(200);
declare varchar(200) str;
declare integer c;
str=compress(m,'','ka');
c=verify(str,lowcase(str));
return(substr(str,c));
end;
method country(varchar(200) m) returns varchar(200);
declare varchar(200) str;
declare integer c;
str=compress(m,'','ka');
c=verify(str,lowcase(str));
return(substr(str,1,c-1));
end;
method age(date _dob,varchar(200) name) returns integer;
declare date dob;
if name='Ante Rebić' then dob=date'1993-09-21';
if name='Patrik Schick' then dob=date'1996-01-21';
else dob=_dob;
return(yrdif(to_double(dob),today()));
end;
method opponent(varchar(200) m) returns varchar(200);
declare varchar(200) str;
declare integer c;
str=compress(m,'','ka');
c=verify(str,lowcase(str));
return(substr(str,c));
end;
endpackage;
run;
quit;

proc ds2;
thread dd / overwrite=yes;
keep PLAYER_ID SHIRT_N PLAYER_NAME AGE HEIGHT FOOT COUNTRY SQUAD SQUAD_RANKING OPPONENT OPPONENT_RANKING M_WEEKDAY M_MONTH
M_SEASON YEAR COMPETITION_N ROUND_N VENUE_N STARTER STRIKER PENALTY PENALTY_SHOOTER MINUTES GOALS;
declare package mm m();
declare varchar(6) player_id country;declare varchar(200) player_name squad;
declare integer shirt_n age height squad_ranking opponent_ranking m_weekday m_month m_season year competition_n round_n
venue_n minutes goals;declare tinyint foot starter striker penalty penalty_shooter;
retain penalty_shooter 0;
method init();
declare integer rc;
end;
method run();
   declare integer rc;
   set o2 o4 o6 o8 o10 o12 o14 o16 o18;
   squad=m.squad(_squad);
   country=m.country(_squad);
   shirt_n=m.shirt_n(name);
   player_id=upcase(catx('-',country,SHIRT_N));
   player_name=name;
   age=m.age(dob,name);
   foot=m.foot(name);
   year=year(to_double(date_1));
   squad_ranking=m.squad_ranking(squad,year);
   squad=scan(_squad,2,' ','s');
   opponent=m.opponent(opponent);
   opponent_ranking=m.squad_ranking(opponent,year);
   m_weekday=weekday(to_double(date_1));
   m_month=month(to_double(date_1));
   m_season=m.m_season(m_month);
   competition_n=m.competition_n(comp);
   round_n=m.round_n(round);
   venue_n=m.venue_n(venue);
   starter=start='Y';
   striker=pos='FW';
   penalty=pk;
   if pk=1 then penalty_shooter=1;
   minutes=min;
   goals=gls;
end;
endthread;
run;
quit;

proc ds2;
data;
declare thread dd d;
method run();
set from d threads=1;
end;
enddata;
run;
quit;
